### ISSUE TITLE
people.set not working

### ISSUE THREAD

**Issue by Juandresyn** [neciu/react-mixpanel#13]
Hey People, I've been using the lib for a couple of weeks and I haven't being able to set people in Mixpanel.

```
this.context.mixpanel.people.set(this.state.uuid, {
      ip: data.ip,
      $distinct_id: this.state.uuid,
      year,
});
```

This is the code I'm using, all the data in the code is working, data.ip, this.state.uuid and year.
But there is no user created in Mixpanel.

Any guess?

Thanks.

**Comment by NickEngmann** [comment]
Did you ever get this working?

**Comment by rennmatthewp** [comment]
Did you call mixpanel.identify? 
https://mixpanel.com/help/reference/javascript#storing-user-profiles

**Comment by neciu** [comment]
I believe this is related to mixpanel library. Closing for now.
