### ISSUE TITLE
Expose mixpanelShape

### ISSUE THREAD

**Issue by TigerC10** [neciu/react-mixpanel#22]
Since we need to populate the `mixpanel` proptype shape in the consumers of this provider, it should be exposed from this library for an easy import.

```javascript
import { MixpanelPropType } from 'react-mixpanel';

SomeConsumer.propTypes = {
  mixpanel: MixpanelPropType,
};
```

**Comment by neciu** [comment]
Since 1.0.5 the shape is exposed.
