### ISSUE TITLE
Error - Failed prop type mixpanel.people

### ISSUE THREAD

**Issue by arshadm** [neciu/react-mixpanel#24]
I have added this component to my project but on startup I am getting the following warning in the console.

checkPropTypes.js:19 Warning: Failed prop type: The prop `mixpanel.people` is marked as required in `MixpanelProvider`, but its value is `undefined`. in MixpanelProvider

Any ideas on how I can fix this warning?

**Comment by arshadm** [comment]
Please ignore, I had initialised with a valid tracking id.

**Comment by RobinHerzog** [comment]
Are you sure it was the tracking id ? All my tokens are corrrects.

**Comment by ack210** [comment]
@RobinHerzog how are you initializing mixpanel?  My issue was that I was calling mixpanel.init from componentDidMount, so it wasn't being initialized in time for the MixpanelProvider component. Once I made sure I didn't render MixpanelProvider until after mixpanel init was called, I stopped getting this error (and mixpanel api started being called correctly).

    class MixpanelInitialized extends PureComponent {
        state = {mixpanelInitialized: false};

        render(){
            const { children } = this.props;
            const { mixpanelInitialized } = this.state;

            return mixpanelInitialized
                ? <MixpanelProvider mixpanel={mixpanel}>{children}</MixpanelProvider>
                : children;
        }

        componentDidMount(){
            mixpanel.init("TOKEN");
            this.setState({mixpanelInitialized: true});
       }
    }
