### ISSUE TITLE
Expose MixpanelContext

### ISSUE THREAD

**Issue by dgw2jr** [neciu/react-mixpanel#26]
Can you expose MixpanelContext so we can use it in functional components like

`const mixpanelContext = useContext(MixpanelContext);`

**Comment by masahitojp** [comment]
👍 we'd like to user contest for React Hooks!!!

**Comment by neciu** [comment]
Covered here: https://github.com/neciu/react-mixpanel/pull/29

Since version 1.0.4 you can get `MixpanelContext` as default export.
